---
- name: Adding postgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Adding postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main

- name: Installing postgresql
  apt:
    name:
      - postgresql-11
      - pgadmin4
      - python-psycopg2 # useful for creating the user (see below)

- name: Creating postgresql uservagrant
  postgresql_user:
    name: "{{ bash_username }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: SUPERUSER,LOGIN
  become_user: postgres

- name: Creating the user database
  postgresql_db:
    name: "{{ bash_username }}"
  become_user: postgres

- name: Configuring postgresql access
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/11/main/pg_hba.conf
  notify: restart postgresql

- name: Enabling postgresql quick connect
  template:
    src: .pgpass.j2
    dest: /home/{{ bash_username }}/.pgpass
    mode: "0600"
  become_user: "{{ bash_username }}"
