---
- hosts: localhost
  vars_files:
    - config_vars.yml
  become: yes
  become_method: sudo

  roles:
    # Should be run first, in this order
    - roles/infrastructure/apt
    - roles/infrastructure/curl
    - roles/infrastructure/snap
    - roles/infrastructure/nodejs
    - roles/infrastructure/python
    - roles/cli/jj

    # Can be runned in any order
    - roles/cli/git
    - roles/cli/htop
    - roles/cli/s-tui
    - roles/cli/vim
    - roles/infrastructure/aws
    - roles/infrastructure/bash
    - roles/infrastructure/cleanup
    - roles/infrastructure/fonts
    - roles/infrastructure/gnome
    - roles/infrastructure/java
    - roles/infrastructure/lol
    - roles/infrastructure/network
    - roles/infrastructure/php
    - roles/infrastructure/postgresql
    - roles/infrastructure/slack
    - roles/infrastructure/vagrant
    - roles/infrastructure/vpn
    #- roles/software/chitubox
    - roles/software/chromium
    - roles/software/discord
    - roles/software/docker
    - roles/software/keybase
    - roles/software/prusaslicer
    - roles/software/spotify
    - roles/software/steam
    - roles/software/tilix
    - roles/software/typora
    - roles/software/vlc
    - roles/software/vscode
