---
- name: Checking if slack is installed
  shell: slack --version
  register: slack_installed
  changed_when: false
  ignore_errors: true
  become_user: '{{ bash_username }}'

- name: Installing slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.1.2-amd64.deb
  when: slack_installed.rc != 0
