# Tasks found here : https://github.com/Dalee/ansible.install-nodejs
- name: Checking node install
  shell: node --version | sed -e 's/^v14.*$/14/'
  register: node_version
  ignore_errors: true
  changed_when: false

- name: Adding repository for node 14
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  when: node_version.stdout is not search('14')

- name: Install node
  apt: name=nodejs state=present

- name: Adding yarn repository keys
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"

- name: Adding yarn
  apt:
    name: yarn
