---
# Authorization : tasks bellow to authenticate to github via ssh
- name: Creating ~/.ssh directory
  file:
    path: "{{ home_directory }}/.ssh"
    state: directory

- name: SSH config
  template:
    src: .ssh_config.j2
    dest: "{{ home_directory }}/.ssh/config"

- name: Generating ssh keys for github
  openssh_keypair:
    path: "{{ home_directory }}/.ssh/ssh_github"
  when: github_access_token|default(None)

- name: Reading ssh public key to authorize
  shell: cat {{ home_directory }}/.ssh/ssh_github.pub
  register: ssh_pub_key
  changed_when: false
  when: github_access_token|default(None)

- name: Adding ssh public key to github
  local_action:
    module: github_key
    name: "{{ github_access_name }}"
    token: "{{ github_access_token }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
  when: github_access_token|default(None)

- name: Checking if this remote is https or ssh
  shell: git remote -v
  register: git_remotes
  changed_when: false

- name: Setting remotes to ssh
  shell: git remote set-url origin git@github.com:web-id-fr/mario.git
  when: git_remotes.stdout is search('https')
