---
- name: Installing NFS server
  apt:
    name: nfs-server

- name: Installing libvpx5
  apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/main/libv/libvpx/libvpx5_1.7.0-3_amd64.deb

- name: Checking if VirtualBox is installed
  shell: VirtualBox --help
  register: virtualbox_installed
  changed_when: false
  ignore_errors: true

- name: Installing VirtualBox
  apt:
    deb: https://download.virtualbox.org/virtualbox/5.2.34/virtualbox-5.2_5.2.34-133893~Ubuntu~bionic_amd64.deb
  when: virtualbox_installed.rc != 0

# - name: Starting virtualbox service
#   service: name=virtualbox state=restarted enabled=yes

- name: Checking if vagrant is installed
  shell: vagrant --version
  register: vagrant_installed
  changed_when: false
  ignore_errors: true

- name: Installing vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
  when: vagrant_installed.rc != 0

- name: Get vagrant plugin list
  shell: vagrant plugin list
  changed_when: false
  register: vagrant_plugins
  become_user: "{{ bash_username }}"

- name: Installing vagrant disksize plugin
  command: vagrant plugin install vagrant-disksize
  when: '"disksize" not in vagrant_plugins.stdout'
  become_user: "{{ bash_username }}"

- name: Installing vagrant notify-forwarder plugin
  command: vagrant plugin install vagrant-notify-forwarder
  when: '"notify-forwarder" not in vagrant_plugins.stdout'
  become_user: "{{ bash_username }}"

- name: Adding vagrant sudoer file to avoid root login
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/vagrant
    validate: "visudo -cf %s"
    mode: 0440
