---
- name: Install steam
  apt: name=steam

- name: Fixing scale factor to fit 4K screen
  replace:
    path: /usr/share/applications/steam.desktopsteam.desktop
    regexp: bin/spotify %U
    replace: bin/spotify --force-scale-factor=2 %U

