---
- name: Installing Node.js 14 (LTS)
  homebrew:
    name: node@14
  when: brew_packages.stdout is not search('node@14')
  register: node_installed

- name: Linking Node.js 14 (LTS)
  homebrew:
    name: node@14
    state: linked
  when: node_installed.changed

- name: Listing globally installed npm packages
  shell: npm list -g --depth 0
  changed_when: false
  failed_when: false
  register: npm_global_packages