---
# jj makes it easy to read/write values in a JSON file :
# https://github.com/tidwall/jj
- name: Checking if jj is installed
  shell: jj --version
  register: jj_installed
  changed_when: false
  ignore_errors: true

- name: Installing jj
  unarchive:
    src: https://github.com/tidwall/jj/releases/download/v1.2.2/jj-1.2.2-linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    extra_opts:
      - "--strip-components=1"
  when: jj_installed.rc != 0