---
- name: Installing git
  homebrew:
    name: git
  when: brew_packages.stdout is not search('git 2')

- name: Installing delta
  homebrew:
    name: git-delta
  when: brew_packages.stdout is not search('git-delta')

- name: Installing git recent
  npm:
    name: git-recent
    global: yes
  when: npm_global_packages.stdout is not search('git-recent')

- name: Installing gitmoji cli
  npm:
    name: gitmoji-cli
    global: true
  when: npm_global_packages.stdout is not search('gitmoji-cli')

- name: Copyting Git configuration
  template:
    src: .gitconfig.j2
    dest: "{{ home_directory }}/.gitconfig"

- name: Copying Git global ignore
  template:
    src: .gitglobalignore.j2
    dest: "{{ home_directory }}/.gitglobalignore"
