---
- name: Checking if the desktop need to be cleaned
  shell: defaults read com.apple.finder CreateDesktop
  register: desktop_check
  failed_when: false

- name: Hiding files on the desktop
  shell: defaults write com.apple.finder CreateDesktop false; killall Finder
  when: desktop_check.stdout != 'false'