---
- name: Installing fira code
  apt: name=fonts-firacode

- name: Adding emoji font repository
  apt_repository:
    repo: ppa:eosrei/fonts
    codename: disco

- name: Installing emoji font
  apt: name=fonts-twemoji-svginot

- name: Checking if JetBrains Mono font file exists
  stat:
    path: ~/.fonts/JetBrainsMono-Regular.ttf
  register: jetbrains_mono_file

- name: Creating font directory
  file:
    path: /home/{{ bash_username }}/.fonts
    state: directory
  become_user: "{{ bash_username }}"

- name: Download JetBrains Mono font
  unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-1.0.0.zip
    dest: /home/{{ bash_username }}/.fonts
    remote_src: yes
  become_user: "{{ bash_username }}"
  when: jetbrains_mono_file.stat.exists == False
  notify: compile font cache
