---
- name: Adding php repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Installing php and dependencies
  apt:
    name:
      - php7.3
      - php7.3-curl
      - php7.3-xml
      - php7.3-pgsql
      - composer

- name: Checking if composer is installed
  shell: composer --version
  register: composer_installed
  changed_when: false
  ignore_errors: true

- name: Downloading composer
  get_url:
    url: https://getcomposer.org/download/1.9.0/composer.phar
    dest: /usr/local/bin/composer
    checksum: sha256:c9dff69d092bdec14dee64df6677e7430163509798895fbd54891c166c5c0875 
    mode: +x
  when: composer_installed.rc != 0

- name: Making sure composer cache directory is writable
  file:
    path: /home/{{ bash_username }}/.composer
    state: directory
    owner: '{{ bash_username }}'
    group: '{{ bash_username }}'
    recurse: yes

- name: Installing php-cs-fixer
  composer:
    command: require
    global_command: yes
    arguments: friendsofphp/php-cs-fixer
