---
- name: Installing yubioath-desktop
  snap:
    name: yubioath-desktop

- name: Installing openvpn
  apt:
    name: openvpn

- name: Creating vpn script directory
  file:
    path: /etc/openvpn/scripts
    state: directory

- name: Copying openvpn script
  copy:
    src: openvpn
    dest: /usr/local/bin/openvpn
    mode: +x

- name: Checking if update-systemd-resolved has been downloaded
  stat:
    path: /etc/openvpn/scripts/update-systemd-resolved
  register: update_systemd_resolved_file

- name: Downloading update-systemd-resolved
  get_url:
    url: https://raw.githubusercontent.com/jonathanio/update-systemd-resolved/master/update-systemd-resolved
    dest: /etc/openvpn/scripts/update-systemd-resolved
    mode: 755
  when: update_systemd_resolved_file.stat.exists == False