---
- name: Checking if Chitubox exists
  stat:
    path: /home/{{ bash_username }}/bin/chitubox
  register: chitubox_binary

- name: Copy Chitubox logo
  copy:
    src: chitubox-logo.png
    dest: /home/{{ bash_username }}/bin/chitubox-logo.png
  become_user: "{{ bash_username }}"

- name: Extracting Chitubox
  unarchive:
    src: "{{ chitubox_archive_path }}"
    dest: /home/{{ bash_username }}/bin
    extra_opts:
      - "--strip-components=1"
    copy: false
  become_user: "{{ bash_username }}"
  when: chitubox_binary.stat.exists == False

- name: Chitubox desktop file
  template:
    src: Chitubox.desktop.j2
    dest: /home/{{ bash_username }}/.local/share/applications/Chitubox.desktop
  become_user: "{{ bash_username }}"
