---
- name: Adding php repository
  apt_repository:
    repo: ppa:ondrej/php
    # codename: disco

- name: Installing php and dependencies
  apt:
    name:
      - php7.4
      - php7.4-curl
      - php7.4-xml
      - php7.4-pgsql
      - php7.4-mbstring
      - php-ast
      - composer

- name: Checking if composer is installed
  shell: composer --version
  register: composer_installed
  changed_when: false
  ignore_errors: true

- name: Downloading composer
  get_url:
    url: https://getcomposer.org/download/1.9.0/composer.phar
    dest: /usr/local/bin/composer
    checksum: sha256:c9dff69d092bdec14dee64df6677e7430163509798895fbd54891c166c5c0875
    mode: +x
  when: composer_installed.rc != 0

- name: Making sure composer cache directory is writable
  file:
    path: /home/{{ bash_username }}/.composer
    state: directory
    owner: "{{ bash_username }}"
    group: "{{ bash_username }}"
    recurse: yes

- name: Checking if php-cs-fixer file exists
  stat:
    path: /home/{{ bash_username }}/.composer/vendor/bin/php-cs-fixer
  register: phpcsfixer_file

- name: Installing php-cs-fixer
  composer:
    command: require
    global_command: yes
    arguments: friendsofphp/php-cs-fixer
  when: phpcsfixer_file.stat.exists == False
  become_user: "{{ bash_username }}"
